# Generated by Django 5.0.7 on 2024-11-13 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marathon', '0002_alter_contestant_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contestant',
            name='species',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
