# Generated by Django 5.0.7 on 2024-11-15 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marathon', '0003_alter_contestant_species'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='marathon',
            name='state',
            field=models.CharField(choices=[('pending', 'Ожидание'), ('in_progress', 'В процессе'), ('final', 'Финал'), ('completed', 'Завершен')], default='pending', max_length=50),
        ),
    ]
