# Generated by Django 5.0.7 on 2024-11-16 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marathon', '0004_alter_event_description_alter_marathon_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='marathon',
            name='participants_number',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
