# Generated by Django 5.0.7 on 2024-11-16 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marathon', '0005_marathon_participants_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='contestant',
            name='dzi',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='image',
            name='author',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
