# Generated by Django 5.0.7 on 2024-11-20 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marathon', '0006_contestant_dzi_alter_image_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nomination',
            name='poll_date',
            field=models.DateField(blank=True),
        ),
    ]
