# Generated by Django 5.0.7 on 2024-11-20 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marathon', '0007_alter_nomination_poll_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nomination',
            name='poll_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
