# Generated by Django 5.0.7 on 2024-12-01 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marathon', '0008_alter_nomination_poll_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='marathon',
            name='description_de',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='marathon',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='marathon',
            name='description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='marathon',
            name='state_de',
            field=models.CharField(choices=[('pending', 'Ожидание'), ('in_progress', 'В процессе'), ('final', 'Финал'), ('completed', 'Завершен')], default='pending', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='marathon',
            name='state_en',
            field=models.CharField(choices=[('pending', 'Ожидание'), ('in_progress', 'В процессе'), ('final', 'Финал'), ('completed', 'Завершен')], default='pending', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='marathon',
            name='state_ru',
            field=models.CharField(choices=[('pending', 'Ожидание'), ('in_progress', 'В процессе'), ('final', 'Финал'), ('completed', 'Завершен')], default='pending', max_length=50, null=True),
        ),
    ]
