# Generated by Django 5.0.7 on 2024-12-23 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marathon', '0010_remove_marathon_state_de_remove_marathon_state_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='title_de',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='title_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='title_ru',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
