# Generated by Django 5.0.7 on 2026-09-26 05:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marathon', '0011_event_title_de_event_title_en_event_title_ru'),
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('tg_id', models.BigIntegerField(blank=True, null=True, unique=True)),
                ('tg_username', models.CharField(blank=True, max_length=100)),
                ('note', models.TextField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name='nomination',
            name='poll_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='nomination',
            name='total_voters',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Nominee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plant', models.CharField(blank=True, help_text='Примечание к растению, если у участника их несколько', max_length=255)),
                ('is_winner', models.BooleanField(default=False)),
                ('votes', models.PositiveIntegerField(blank=True, null=True)),
                ('photo_msgs', models.TextField(blank=True, help_text='Ссылки на посты с фото в Telegram, по одной на строку')),
                ('nomination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nominees', to='marathon.nomination')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nominations', to='marathon.participant')),
            ],
        ),
        migrations.AddField(
            model_name='image',
            name='participant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images', to='marathon.participant'),
        ),
    ]
