# Generated by Django 5.2.17 on 2026-09-27 18:24

from django.db import migrations, models


def copy_ru(apps, schema_editor):
    # modeltranslation читает title_ru/category_ru — переносим туда существующие русские значения
    Nomination = apps.get_model('marathon', 'Nomination')
    for n in Nomination.objects.all():
        n.title_ru, n.category_ru = n.title, n.category
        n.save(update_fields=['title_ru', 'category_ru'])


class Migration(migrations.Migration):

    dependencies = [
        ('marathon', '0013_fix_cyrillic_genus'),
    ]

    operations = [
        migrations.AddField(
            model_name='nomination',
            name='category_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='nomination',
            name='category_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='nomination',
            name='title_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='nomination',
            name='title_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.RunPython(copy_ru, migrations.RunPython.noop),
    ]
