# Generated by Django 5.2.17 on 2026-09-27 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marathon', '0015_review_data_fixes'),
    ]

    operations = [
        migrations.AddField(
            model_name='marathon',
            name='data_table_url',
            field=models.URLField(blank=True, help_text='Таблица данных конкурсного посева (всхожесть, грунт, свет)'),
        ),
        migrations.AddField(
            model_name='marathon',
            name='details',
            field=models.TextField(blank=True, help_text='Формат сезона, если он отличается от обычного (например, «год качества»)'),
        ),
        migrations.AddField(
            model_name='marathon',
            name='details_en',
            field=models.TextField(blank=True, help_text='Формат сезона, если он отличается от обычного (например, «год качества»)', null=True),
        ),
        migrations.AddField(
            model_name='marathon',
            name='details_ru',
            field=models.TextField(blank=True, help_text='Формат сезона, если он отличается от обычного (например, «год качества»)', null=True),
        ),
        migrations.AddField(
            model_name='marathon',
            name='format_note',
            field=models.CharField(blank=True, help_text='Коротко для карточки вместо числа конкурсных видов', max_length=255),
        ),
        migrations.AddField(
            model_name='marathon',
            name='format_note_en',
            field=models.CharField(blank=True, help_text='Коротко для карточки вместо числа конкурсных видов', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='marathon',
            name='format_note_ru',
            field=models.CharField(blank=True, help_text='Коротко для карточки вместо числа конкурсных видов', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='marathon',
            name='sowing_table_url',
            field=models.URLField(blank=True, help_text='Таблица посевов'),
        ),
    ]
