# Generated by Django 5.2.17 on 2026-09-27 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marathon', '0020_marathon_2026_stages_note'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marathon',
            name='state',
        ),
    ]
