# Generated by Django 5.2.17 on 2026-09-27 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marathon', '0021_auto_marathon_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='marathon',
            name='details_de',
            field=models.TextField(blank=True, help_text='Формат сезона, если он отличается от обычного (например, «год качества»)', null=True),
        ),
        migrations.AddField(
            model_name='marathon',
            name='format_note_de',
            field=models.CharField(blank=True, help_text='Коротко для карточки вместо числа конкурсных видов', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='nomination',
            name='category_de',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='nomination',
            name='title_de',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
